### ISSUE TITLE
Flush the input buffer when we leave input mode but found nothing

### ISSUE THREAD

**Issue by victorlin** [brunchmade/mojito#15]
When you type something like this

`:)`

and press ESC or enter, it would be nice to flush the input buffer instead of reset it

**Comment by victorlin** [comment]
Thought about this feature, `ESC` is for `cancelOperation` command, and it usually means user wanting to cancel the operation literally, so I think it's better to drop the input buffer.

Instead, when you press `Enter`, that means you want to submit it. So I change the key to `Enter` instead.

/cc @lg

**Comment by lg** [comment]
hm. i'm pressing `ESC` to close the dialog and keep the ":)" that i already typed. i think ESC would make sense here. what about both `ESC` an `Enter`?

**Comment by victorlin** [comment]
@lg yo, problem fixed 😎

**Comment by lg** [comment]
:) :) :)
